FROM python:3.7.3
RUN mkdir -p /backend
WORKDIR /backend
COPY . /backend
RUN pip install flask
RUN pip install flask_cors
RUN pip install sqlalchemy
RUN pip install psycopg2-binary
RUN pip install flask-restplus==0.13.0
ENTRYPOINT ["python"]
CMD ["service/run.py"]
