version: '3'
services:
    web:
        build: .
        command: flask run --host=0.0.0.0 --port=8000
        ports:
            - 8000:8000
        environment:
            - FLASK_APP=app.py
        env_file:
            - env.list
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_USER=polls
            - POSTGRES_PASSWORD=hearmeroar
            - POSTGRES_DB=polls_db
        volumes:
            - flask_polls_data:/var/lib/postgresql/data

volumes:
    flask_polls_data:
